workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "web"'

image: docker:stable
services:
  - docker:stable-dind

stages:
  - build

variables:
  IMAGE_NAME: smujaddid/rancher-letsencrypt

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

Build:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - changes:
      - "VERSION"
  script:
    - IMAGE_VERSION=$(cat VERSION)
    - docker build --pull -t $IMAGE_NAME:$IMAGE_VERSION -f ./dockerfiles/Dockerfile .
    - docker tag $IMAGE_NAME:$IMAGE_VERSION $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$IMAGE_VERSION
    - docker push $IMAGE_NAME:latest
