FROM alpine:3.12

RUN apk -U upgrade --no-cache \
    && apk -U add --no-cache \
        bash \
        ca-certificates \
        curl \
        tzdata

ADD dist/rancher-letsencrypt /usr/bin/rancher-letsencrypt

RUN chmod +x /usr/bin/rancher-letsencrypt

CMD [ "/usr/bin/rancher-letsencrypt", "-debug", "-test-mode" ]

EXPOSE 80
